### ISSUE TITLE
[Вопрос] Поддержка ECC на Jingsha X99

### ISSUE THREAD

**Issue by ghost** [ThinkPadThink/Guide2011-3#1]
Доброго времени суток!
Нигде в сети не смог найти информации о фактической работоспособности ECC на плате Jingsha X99. Вопрос не о поддержке регистровой памяти, а о фактической работоспособности коррекции - т.е. логировании исправленных и обнаруженных ошибок и поддержке скраббинга, ибо китаец на плате мог все лишние дорожки DIMM не развести, отключив коррекцию и использовав 64 бита шины из 72. Такое под виндами можно увидеть в AIDA64 (все фото не мои, они [отсюда](https://hardwarecanucks.com/cpu-motherboard/ecc-memory-amds-ryzen-deep-dive/)):
![Ryzen_ECC-16](https://user-images.githubusercontent.com/16356368/73425092-9e89fd00-4341-11ea-9b05-3ce65bb36133.png)
Под линухами же можно это увидеть в dmesg:
![Ryzen_ECC-27](https://user-images.githubusercontent.com/16356368/73425252-27089d80-4342-11ea-9af3-ccd344064334.png)
Если осталась возможность связаться с владельцем такой платы, работающей с регистровой памятью, прошу с ним связаться и узнать, или дать его контакт.

**Comment by ThinkPadThink** [comment]
На счёт Джингши не могу подсказать, ПлексХД Х99 показывает вот так со слов пользователей:
![15807048273670](https://user-images.githubusercontent.com/25593106/73781904-276dc200-47a2-11ea-9230-07ca4d5b351d.png)

**Comment by ghost** [comment]
Понял, спасибо!
Разводка плат, конечно, может быть существенно разной, да и память DDR4. Но снимок не воодушевляет, всё связанное с коррекцией отключено. Хотя это мог и пользователь сделать в биосе, хрен угадаешь.
Плату заказал сейчас на попробовать, благо дешевая. Как получу и увижу своими глазами - отпишусь тут и закрою.

**Comment by ThinkPadThink** [comment]
Возможно всё выключили в UEFI. Но луше бы взяли Хуананжи X99 F8. По джингшам Х99 вообще мало чего известно.

**Comment by ghost** [comment]
Да задачи чуть другие (кластер Proxmox), поэтому цена и доступность памяти решают.
8x32GB DDR3 с немецкого ибея в районе £500, DDR4 уже тянется к £1000.
Потом это отмасшабировать на несколько машин.
Если джингша не пойдёт - всегда можно вернуться к б/у двухсокетовым на 2011, а перед приличными закупками не лень поэкспериментировать на плате за условные сто баксов.

**Comment by ghost** [comment]
ECC работоспособен, конфигурится из биоса:
![Снимок экрана от 2020-03-15 21 13 42](https://user-images.githubusercontent.com/16356368/76707652-164d9480-6702-11ea-8e32-eedfa787a170.png)

С драйвером ядра для работы с ECC пока не разобрался. Ядро видит, что память ECC, но не участвует в коррекции ошибок:
![Снимок экрана от 2020-03-15 21 20 50@2x](https://user-images.githubusercontent.com/16356368/76707735-ddfa8600-6702-11ea-966c-481e7fb769cb.png)

Кроме того, джингша успешно стартанула с 256 гигов самсунговой DDR3 RDIMM (не LRDIMM, такую память не проверял!).

Ещё у джингши новый родной [биос](http://www.jingsha668.com/uploads/soft/X99.zip), в котором есть оверклокинг и управление таймингами.
Как окончательно прочувствую, что это за зверь - накидаю пулл-реквест.

**Comment by ghost** [comment]
На поверку, Jingsha зверем оказалась весьма дурным, не рекомендую к покупке.
Имел проблемы со стабильностью, с периодичностью от полумесяца до пары месяцев плата намертво повисала.
Не решилась проблема ни игрищами с биосом, ни напайкой развязочных конденсаторов сзади сокета.
Не знаю, моя ли пробная плата была проблемной, либо они все с "особенностью".

Имеющееся железо и Proxmox успешно перетащил на платы Huananzhi X99 T8, что весьма близко к совету @ThinkPadThink, разве что поновее (на момент рекомендации её ещё не было) и с DDR3. Прошил на платы биос последний, в котором ещё не был отключен ECC. По диагностике полный фарш, в линуксе edac подхватывает контроллеры памяти и читает CE и UE, также успешно работает rasdaemon и собирает остальную диагностику из кишков железа.
На плате адекватные IOMMU группы (вообще не придраться) и нет проблем с ремаппингом прерываний PCIe в ВМ.
По железу пока ничего не трогал, никаких игрищ с паяльником, хотя экономные китаёзы также оставили эту плату без развязки по питанию проца.
Из косяков - вентиляторы мосфетов плат за весьма краткий период стали чувствовать себя не очень. Надо что-то придумывать.
Таких серверов насобирал несколько штук, работаем на них, пока полёт нормальный.

**Comment by ThinkPadThink** [comment]
@InviteCiel Если вам нужно, хуананжи для своих x99 плат продаёт отдельно радиаторы за 700 рублей
aliexpress.ru/item/4001276193611.html

**Comment by ghost** [comment]
Отличная новость! Спасибо!
